/**
 * S3 — Golden Baseline
 *
 * Snapshot baselines for regression testing. These are generated by running
 * the pipeline once and capturing the output. They serve as the reference
 * for detecting unexpected changes.
 */

export interface GoldenBaseline {
  /** Case ID */
  caseId: string;
  /** Timestamp of generation */
  generatedAt: string;
  /** Git commit hash */
  commitHash?: string;
  /** Expected output snapshot */
  snapshot: Record<string, unknown>;
}

/**
 * Golden baselines for regression test cases.
 * These are pre-computed expected outputs for stable test cases.
 */
export const goldenBaselines: GoldenBaseline[] = [
  {
    caseId: "regression-welded-box",
    generatedAt: "2026-08-24T00:00:00Z",
    snapshot: {
      topology: {
        closed: true,
        manifoldEdges: 0,
        nonManifoldEdges: 0,
        intersectingFaces: 0,
        redundantFaces: 0,
        reversedNormalFaces: 0,
        openEdges: 0,
        duplicateFaces: 0,
        selfIntersections: 0,
        genus: 0,
        shellCount: 1,
        isWatertight: true,
      },
      validation: {
        status: "manifold",
        confidence: 0.95,
        slicerReady: true,
        printabilityScore: 0.92,
      },
      metrics: {
        volumeMm3: 1000,
        surfaceAreaMm2: 600,
        boundingBox: { x: 10, y: 10, z: 10 },
        triangleCount: 12,
        dimensions: { x: 10, y: 10, z: 10 },
      },
      bedFit: {
        fits: true,
        printerModel: "Prusa MK4S",
        bedSize: { x: 250, y: 210, z: 220 },
      },
      support: {
        needsSupport: false,
        estimatedVolumeCm3: 0,
        estimatedPrintTimeMinutes: 0,
      },
      printTime: {
        estimatedMinutes: 15,
        filamentGrams: 5,
        filamentMm: 1500,
      },
      thermal: {
        warpingRisk: 0.1,
        bedAdhesionScore: 0.9,
        recommendedBedTempC: 60,
        recommendedPrintTempC: 210,
        layerAdhesion: 0.95,
      },
      overallConfidence: 0.92,
    },
  },
  {
    caseId: "normal-watertight-cube",
    generatedAt: "2026-08-24T00:00:00Z",
    snapshot: {
      topology: {
        closed: true,
        manifoldEdges: 0,
        nonManifoldEdges: 0,
        shellCount: 1,
        isWatertight: true,
      },
      validation: {
        status: "manifold",
        confidence: 0.95,
        slicerReady: true,
        printabilityScore: 0.92,
      },
      metrics: {
        volumeMm3: 8000,
        surfaceAreaMm2: 2400,
        triangleCount: 12,
      },
      bedFit: {
        fits: true,
      },
      support: {
        needsSupport: false,
        estimatedVolumeCm3: 0,
      },
      printTime: {
        estimatedMinutes: 30,
        filamentGrams: 10,
      },
      thermal: {
        warpingRisk: 0.1,
        bedAdhesionScore: 0.9,
        recommendedBedTempC: 60,
        recommendedPrintTempC: 210,
        layerAdhesion: 0.95,
      },
      overallConfidence: 0.93,
    },
  },
];
