/**
 * S3 — Golden Baseline
 *
 * Snapshot baselines for regression testing. These are generated by running
 * the pipeline once and capturing the output. They serve as the reference
 * for detecting unexpected changes.
 */

export interface GoldenBaseline {
  /** Case ID */
  caseId: string;
  /** Timestamp of generation */
  generatedAt: string;
  /** Git commit hash */
  commitHash?: string;
  /** Expected output snapshot */
  snapshot: Record<string, unknown>;
}

/**
 * Golden baselines for regression test cases.
 * These are pre-computed expected outputs for stable test cases.
 * Updated with real PrusaSlicer data (S1c integration).
 */
export const goldenBaselines: GoldenBaseline[] = [
  {
    caseId: "regression-welded-box",
    generatedAt: "2026-08-24T10:50:41.042Z",
    snapshot: {
      topology: {
        isManifold: true,
        manifoldEdgeCount: 12,
        nonManifoldEdgeCount: 0,
        boundaryEdgeCount: 0,
        shellCount: 1,
        triangleCount: 12,
      },
      validation: {
        isWatertight: true,
        holeCount: 0,
        flippedNormalFaceCount: 0,
        totalFaceCount: 12,
        flippedNormalRatio: 0,
        normalOrientation: "consistent_outward",
        degenerateFaceCount: 0,
      },
      metrics: {
        meshVolumeMm3: 8000,
        surfaceAreaMm2: 2400,
        boundingBoxDimensionsMm: { x: 20, y: 20, z: 20 },
        triangleCount: 12,
      },
      bedFit: {
        fits: true,
        printerProfile: {
          id: "bambu_x1c",
          name: "Bambu Lab X1C",
          widthMm: 256,
          depthMm: 256,
          heightMm: 256,
        },
      },
      support: {
        totalSupportVolumeMm3: 0,
        supportFaceCount: 0,
        difficulty: "none",
      },
      printTime: {
        estimatedPrintTimeMinutes: 13.9,
        materialWeightGrams: 4.45,
        layerCount: 66,
        source: "slicer",
        slicerId: "prusaslicer",
      },
      thermal: null,
    },
    overallConfidence: 0.9,
  },
  {
    caseId: "normal-watertight-cube",
    generatedAt: "2026-08-24T10:50:41.042Z",
    snapshot: {
      topology: {
        isManifold: true,
        manifoldEdgeCount: 12,
        nonManifoldEdgeCount: 0,
        boundaryEdgeCount: 0,
        shellCount: 1,
        triangleCount: 12,
      },
      validation: {
        isWatertight: true,
        holeCount: 0,
        flippedNormalFaceCount: 0,
        totalFaceCount: 12,
        flippedNormalRatio: 0,
        normalOrientation: "consistent_outward",
        degenerateFaceCount: 0,
      },
      metrics: {
        meshVolumeMm3: 8000,
        surfaceAreaMm2: 2400,
        boundingBoxDimensionsMm: { x: 20, y: 20, z: 20 },
        triangleCount: 12,
      },
      bedFit: {
        fits: true,
        printerProfile: {
          id: "bambu_x1c",
          name: "Bambu Lab X1C",
          widthMm: 256,
          depthMm: 256,
          heightMm: 256,
        },
      },
      support: {
        totalSupportVolumeMm3: 0,
        supportFaceCount: 0,
        difficulty: "none",
      },
      printTime: {
        estimatedPrintTimeMinutes: 13.9,
        materialWeightGrams: 4.45,
        layerCount: 66,
        source: "slicer",
        slicerId: "prusaslicer",
      },
      thermal: null,
    },
    overallConfidence: 0.9,
  },
];
