import { describe, it, expect } from 'vitest';
import { parseToolpath } from '../toolpath';

const GCODE = [
  '; generated by PrusaSlicer 2.9.6',
  'G28 ; home',
  'G1 Z5 F5000',
  'G92 E0',
  ';LAYER_CHANGE',
  ';Z:0.35',
  ';HEIGHT:0.35',
  'G1 X81.2 Y85.8 F7800', // travel — dropped
  'G1 X82.9 Y84.4 E2.20349', // skirt extrusion
  'G1 X86.0 Y83.6 E2.48827',
  'G1 E7.75 F2400', // retraction-ish (no XY) — dropped
  'G92 E0',
  ';LAYER_CHANGE',
  ';Z:0.65',
  ';HEIGHT:0.3',
  'G1 X88.0 Y90.9 F7800', // travel — dropped
  'G1 X88.0 Y109.0 E11.30', // perimeter extrusion
  'G1 X86.9 Y109.0 E11.40',
  '',
].join('\n');

describe('parseToolpath', () => {
  it('keeps extrusion moves and drops travels', () => {
    const tp = parseToolpath(GCODE);
    expect(tp.layers).toHaveLength(2);
    expect(tp.layers[0].zMm).toBeCloseTo(0.35, 5);
    expect(tp.layers[0].points.length / 3).toBe(2); // 2 skirt points
    expect(tp.layers[1].zMm).toBeCloseTo(0.65, 5);
    expect(tp.layers[1].points.length / 3).toBe(2); // 2 perimeter points
    expect(tp.totalPoints).toBe(4);
    expect(tp.decimated).toBe(false);
    // First skirt point coordinates preserved exactly.
    expect(tp.layers[0].points[0]).toBeCloseTo(82.9, 5);
    expect(tp.layers[0].points[1]).toBeCloseTo(84.4, 5);
  });

  it('resyncs E on G92 (no false extrusion after reset)', () => {
    const tp = parseToolpath(GCODE);
    // E7.75 line has no XY → dropped; post-G92 E11.30 > 0 → kept.
    const l1 = tp.layers[1];
    expect(l1.points.length / 3).toBe(2);
  });

  it('returns empty layers for travel-only gcode', () => {
    const tp = parseToolpath('G28\nG1 X10 Y10 F7800\nG1 Z5\n');
    expect(tp.totalPoints).toBe(0);
    expect(tp.layers).toHaveLength(0);
  });

  it('decimates huge paths per layer, keeping every layer', () => {
    const lines = [';LAYER_CHANGE', ';Z:0.2'];
    for (let i = 0; i < 1000; i++) lines.push(`G1 X${i} Y${i} E${i * 0.1 + 0.1}`);
    lines.push(';LAYER_CHANGE', ';Z:0.4');
    for (let i = 0; i < 10; i++) lines.push(`G1 X${i} Y${i} E${100 + i * 0.1 + 0.1}`);
    const tp = parseToolpath(lines.join('\n'), 100);
    expect(tp.decimated).toBe(true);
    expect(tp.totalPoints).toBeLessThanOrEqual(100);
    expect(tp.layers).toHaveLength(2); // small layer survives decimation
    expect(tp.layers[1].points.length / 3).toBeGreaterThan(0);
  });

  it('parses PrusaSlicer short decimals without leading zero (Z.35)', () => {
    const tp = parseToolpath(
      [';LAYER_CHANGE', ';Z:0.35', 'G1 Z.35 F7800', 'G1 X1 Y1 E0.5'].join('\n')
    );
    expect(tp.layers).toHaveLength(1);
    expect(tp.layers[0].points[2]).toBeCloseTo(0.35, 5);
  });

  it('handles legacy ;LAYER:n markers', () => {
    const tp = parseToolpath([';LAYER:0', ';Z:0.2', 'G1 X1 Y1 E0.5', ';LAYER:1', ';Z:0.4', 'G1 X2 Y2 E1.0'].join('\n'));
    expect(tp.layers).toHaveLength(2);
    expect(tp.layers[1].zMm).toBeCloseTo(0.4, 5);
  });
});
