/**
 * Slicer bridge tests: G-code metadata parsing, layer extraction, binary-STL
 * bed-drop, and the CLI adapter (with `execFile` injected so no real slicer is
 * required).
 */
import { describe, it, expect, vi } from 'vitest';
import { writeFileSync, existsSync, rmSync } from 'node:fs';
import { execFile } from 'node:child_process';
import { createServer } from 'node:http';
import { tmpdir } from 'node:os';
import path from 'node:path';
import express from 'express';
import {
  createSlicerAdapter,
  dropStlToBed,
  parseGCodeMetadata,
  parseLayers,
  MAX_TIMEOUT_MS,
} from '../../server/slicerBridge';
import { createSlicerRouter } from '../../server/slicerRouter';

const PRUSA_GCODE = [
  '; generated by PrusaSlicer',
  '; estimated printing time (normal mode) = 0m 42s',
  '; estimated printing time (silent mode) = 1h 2m 3s',
  '; filament used [g] = 0.79',
  '; layer_height = 0.2',
  '; total layers count = 21',
  ';LAYER:0',
  ';Z:0.2',
  'G1 Z0.2',
  ';LAYER:1',
  ';Z:0.4',
  'G1 Z0.4',
  '',
].join('\n');

/** Build a minimal binary STL from a list of triangles. */
function buildBinaryStl(triangles: Array<{ vertices: [number, number, number][] }>): Uint8Array {
  const buf = new ArrayBuffer(80 + 4 + triangles.length * 50);
  const view = new DataView(buf);
  view.setUint32(80, triangles.length, true);
  let off = 84;
  for (const t of triangles) {
    for (let i = 0; i < 12; i++) view.setUint8(off + i, 0); // normal = 0
    for (let v = 0; v < 3; v++) {
      view.setFloat32(off + 12 + v * 12, t.vertices[v][0], true);
      view.setFloat32(off + 16 + v * 12, t.vertices[v][1], true);
      view.setFloat32(off + 20 + v * 12, t.vertices[v][2], true);
    }
    view.setUint16(off + 48, 0, true);
    off += 50;
  }
  return new Uint8Array(buf);
}

describe('parseGCodeMetadata', () => {
  it('parses PrusaSlicer-style header comments', () => {
    const m = parseGCodeMetadata(PRUSA_GCODE);
    expect(m.printTimeMinutes).toBeCloseTo(0.7, 5);
    expect(m.filamentGrams).toBeCloseTo(0.79, 5);
    expect(m.layerCount).toBe(21);
    expect(m.layerHeightMm).toBeCloseTo(0.2, 5);
  });

  it('parses BambuStudio-style longer times', () => {
    const m = parseGCodeMetadata(
      '; estimated printing time (normal mode) = 27m 25s\n; filament used [g] = 3.24\n; total layers count = 98',
    );
    expect(m.printTimeMinutes).toBeCloseTo(27.42, 1);
    expect(m.filamentGrams).toBeCloseTo(3.24, 5);
    expect(m.layerCount).toBe(98);
  });

  it('handles hour components', () => {
    const m = parseGCodeMetadata('; estimated printing time (normal mode) = 1h 2m 3s');
    expect(m.printTimeMinutes).toBeCloseTo(62.05, 5);
  });

  it('returns safe defaults for unparseable input', () => {
    const m = parseGCodeMetadata('G28\nG1 X0 Y0');
    expect(m.printTimeMinutes).toBe(0);
    expect(m.filamentGrams).toBe(0);
    expect(m.layerCount).toBe(0);
    expect(m.layerHeightMm).toBeNull();
  });
});

describe('parseLayers', () => {
  it('pairs LAYER markers with Z values and computes layer height', () => {
    const layers = parseLayers(PRUSA_GCODE);
    expect(layers).toHaveLength(2);
    expect(layers[0]).toMatchObject({ layerNumber: 0, zMm: 0.2, heightMm: 0 });
    expect(layers[1]).toMatchObject({ layerNumber: 1, zMm: 0.4, heightMm: 0.2 });
  });
});

describe('dropStlToBed', () => {
  it('translates a binary STL so minZ = 0', () => {
    const stl = buildBinaryStl([{ vertices: [[0, 0, 5], [10, 0, 6], [0, 10, 7]] }]);
    const dropped = dropStlToBed(stl);
    expect(dropped.byteLength).toBe(stl.byteLength);

    const view = new DataView(dropped.buffer, dropped.byteOffset, dropped.byteLength);
    // v1.z → 0, v2.z → 1, v3.z → 2 (offset: 84 + 20/32/44)
    expect(view.getFloat32(84 + 20, true)).toBeCloseTo(0, 5);
    expect(view.getFloat32(84 + 32, true)).toBeCloseTo(1, 5);
    expect(view.getFloat32(84 + 44, true)).toBeCloseTo(2, 5);
  });

  it('returns the input unchanged when already on the bed', () => {
    const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
    expect(dropStlToBed(stl)).toBe(stl);
  });
});

describe('createSlicerAdapter', () => {
  it('invokes the slicer CLI and returns parsed metadata', async () => {
    const exec = vi.fn((cmd: string, args: string[], _opts: unknown, cb: (err: Error | null, stdout: string, stderr: string) => void) => {
      const outIdx = args.indexOf('--output');
      writeFileSync(args[outIdx + 1], PRUSA_GCODE);
      cb(null, '', '');
      return {} as never;
    });

    const adapter = createSlicerAdapter(
      { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer', printerPreset: 'MK3S', layerHeightMm: 0.2 },
      { execFile: exec as unknown as typeof execFile },
    );

    const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
    const result = await adapter.slice({
      stlBytes: stl,
      fileName: 'part.gcode',
      profile: { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
    });

    expect(exec).toHaveBeenCalledTimes(1);
    expect(exec.mock.calls[0][0]).toBe('/usr/bin/prusa-slicer');
    expect(exec.mock.calls[0][1]).toContain('--export-gcode');
    expect(exec.mock.calls[0][1]).toContain('--output');

    expect(result.fileName).toBe('part.gcode');
    expect(result.metadata.printTimeMinutes).toBeCloseTo(0.7, 5);
    expect(result.metadata.filamentGrams).toBeCloseTo(0.79, 5);
    expect(result.metadata.layerCount).toBe(21);
    expect(result.layers).toHaveLength(2);
  });

  it('drops the mesh to the bed before slicing when requested', async () => {
    const exec = vi.fn((_cmd: string, args: string[], _opts: unknown, cb: (err: Error | null, stdout: string, stderr: string) => void) => {
      const outIdx = args.indexOf('--output');
      writeFileSync(args[outIdx + 1], PRUSA_GCODE);
      cb(null, '', '');
      return {} as never;
    });

    const adapter = createSlicerAdapter(
      { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
      { execFile: exec as unknown as typeof execFile },
    );

    const stl = buildBinaryStl([{ vertices: [[0, 0, 50], [10, 0, 51], [0, 10, 52]] }]); // raised 50 mm
    const result = await adapter.slice({
      stlBytes: stl,
      autoDropToBed: true,
      profile: { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
    });

    expect(result.warnings.some((w) => w.includes('autoDropToBed'))).toBe(true);
    expect(exec).toHaveBeenCalledTimes(1);
  });

  it('reports an error when the slicer subprocess fails', async () => {
    const exec = vi.fn((_cmd: string, _args: string[], _opts: unknown, cb: (err: Error | null, stdout: string, stderr: string) => void) => {
      cb(new Error('ENOENT'), '', 'slicer not found');
      return {} as never;
    });

    const adapter = createSlicerAdapter(
      { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
      { execFile: exec as unknown as typeof execFile },
    );

    const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
    await expect(
      adapter.slice({ stlBytes: stl, profile: { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' } }),
    ).rejects.toThrow(/Slicer \/usr\/bin\/prusa-slicer failed/);
  });
});

describe('Slicer security hardening', () => {
  it('refuses to run a non-absolute binary path', async () => {
    const adapter = createSlicerAdapter({ id: 'prusaslicer', binary: 'sh' });
    const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
    await expect(
      adapter.slice({ stlBytes: stl, profile: { id: 'prusaslicer', binary: 'sh' } }),
    ).rejects.toThrow(/non-absolute/);
  });

  it('isAvailable returns false for a non-absolute binary', async () => {
    const adapter = createSlicerAdapter({ id: 'prusaslicer', binary: 'prusa-slicer' });
    expect(await adapter.isAvailable()).toBe(false);
  });

  it('clamps client-supplied timeouts to MAX_TIMEOUT_MS', async () => {
    const exec = vi.fn(
      (_cmd: string, args: string[], opts: { timeout?: number }, cb: (err: Error | null, stdout: string, stderr: string) => void) => {
        const outIdx = args.indexOf('--output');
        writeFileSync(args[outIdx + 1], PRUSA_GCODE);
        cb(null, '', '');
        return {} as never;
      },
    );
    const adapter = createSlicerAdapter(
      { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
      { execFile: exec as unknown as typeof execFile },
    );
    const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
    await adapter.slice({
      stlBytes: stl,
      profile: { id: 'prusaslicer', binary: '/usr/bin/prusa-slicer' },
      timeoutMs: 9_999_999,
    });
    expect(exec.mock.calls[0][2]).toMatchObject({ timeout: MAX_TIMEOUT_MS });
  });

  it('dropStlToBed refuses a malformed triangle count instead of reading out of bounds', () => {
    const buf = new Uint8Array(88); // header + count, but no triangles
    new DataView(buf.buffer).setUint32(80, 0xffffff, true); // claims ~16M triangles
    expect(dropStlToBed(buf)).toBe(buf);
  });
});

describe('slicerRouter security', () => {
  async function withRouter(fn: (baseUrl: string) => Promise<void>): Promise<void> {
    const app = express();
    app.use('/api/slice', createSlicerRouter());
    const server = createServer(app);
    await new Promise<void>((resolve) => server.listen(0, resolve));
    const addr = server.address() as { port: number };
    try {
      await fn(`http://127.0.0.1:${addr.port}`);
    } finally {
      await new Promise<void>((resolve) => server.close(() => resolve()));
    }
  }

  it('ignores a client-supplied binary path and extraArgs — no RCE', async () => {
    const sentinel = path.join(tmpdir(), 'slicer-rce-sentinel');
    rmSync(sentinel, { force: true });

    // Pin the whitelist to a nonexistent path so discovery deterministically
    // finds nothing on any machine (and never probes well-known app paths).
    const prev = process.env.SLICER_PATHS;
    process.env.SLICER_PATHS = '/nonexistent/slicer';
    try {
      const stl = buildBinaryStl([{ vertices: [[0, 0, 0], [10, 0, 0], [0, 10, 0]] }]);
      await withRouter(async (base) => {
        const res = await fetch(`${base}/api/slice`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            stlBase64: Buffer.from(stl).toString('base64'),
            slicer: 'prusaslicer',
            // Attempted RCE payload — must be ignored entirely.
            binary: '/bin/sh',
            extraArgs: ['-c', `echo pwned > ${sentinel}`],
          }),
        });
        expect(res.status).toBe(404); // slicer-not-found, not a shell result
        expect(existsSync(sentinel)).toBe(false); // /bin/sh was never executed
      });
    } finally {
      rmSync(sentinel, { force: true });
      if (prev === undefined) delete process.env.SLICER_PATHS;
      else process.env.SLICER_PATHS = prev;
    }
  });

  it('rejects an empty payload with 400', async () => {
    await withRouter(async (base) => {
      const res = await fetch(`${base}/api/slice`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });
      expect(res.status).toBe(400);
    });
  });
});
